version: 2

multi-ecosystem-groups:
  routine-updates:
    schedule:
      interval: weekly
      day: monday
      time: '00:00'
      timezone: Etc/UTC

updates:
  - package-ecosystem: nuget
    directory: /
    patterns: ['*']
    multi-ecosystem-group: routine-updates

  - package-ecosystem: dotnet-sdk
    directory: /
    patterns: ['*']
    multi-ecosystem-group: routine-updates

  - package-ecosystem: github-actions
    directory: /
    patterns: ['*']
    multi-ecosystem-group: routine-updates
