using System.Text;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Media;
using Avalonia.VisualTree;
using DownKyi.CustomControl;
using DownKyi.Views.Dialogs;

namespace DownKyi.Desktop.Tests;

public sealed class ReleaseNotesMarkdownViewTests
{
    private static readonly string[] ExpectedNestedListMarkers = ["3.", "•", "4.", "5."];

    [AvaloniaFact]
    public void RepresentativeReleaseBodyRendersSemanticsWithoutActiveContent()
    {
        DesktopTestResources.EnsureProductThemeResources();
        var view = new ReleaseNotesMarkdownView
        {
            Markdown = """
                # DownKyi vNext

                > 升级提示

                - **修复**下载问题
                - 支援 `inline code`

                [完整变更](https://github.com/crazysmile-PhD/downkyicore)
                ![tracking pixel](https://example.test/pixel.png)
                <!-- generated by git-cliff -->
                """
        };
        var window = new Window
        {
            Content = view
        };

        try
        {
            window.Show();
            window.UpdateLayout();

            var descendants = view.GetVisualDescendants().ToArray();
            var visibleText = string.Join(
                '\n',
                descendants.OfType<TextBlock>().Select(GetText));

            Assert.Contains(
                descendants.OfType<TextBlock>(),
                textBlock => textBlock.Classes.Contains(ReleaseNotesMarkdownView.HeadingClass) &&
                             GetText(textBlock) == "DownKyi vNext");
            Assert.Contains(
                descendants.OfType<Border>(),
                border => border.Classes.Contains(ReleaseNotesMarkdownView.QuoteClass));
            Assert.Contains(
                descendants.OfType<TextBlock>(),
                textBlock => textBlock.Classes.Contains(ReleaseNotesMarkdownView.ListMarkerClass) &&
                             textBlock.Text == "•");
            Assert.Contains(
                GetInlines(descendants.OfType<TextBlock>()),
                inline => inline.Classes.Contains(ReleaseNotesMarkdownView.StrongClass));
            Assert.Contains(
                GetInlines(descendants.OfType<TextBlock>()),
                inline => inline.Classes.Contains(ReleaseNotesMarkdownView.InlineCodeClass));
            Assert.Contains(
                GetInlines(descendants.OfType<TextBlock>()),
                inline => inline.Classes.Contains(ReleaseNotesMarkdownView.LinkClass));
            Assert.Contains("tracking pixel", visibleText, StringComparison.Ordinal);
            Assert.DoesNotContain("generated by git-cliff", visibleText, StringComparison.Ordinal);
            Assert.DoesNotContain("https://example.test/pixel.png", visibleText, StringComparison.Ordinal);
            Assert.Empty(descendants.OfType<Image>());
            Assert.Empty(descendants.OfType<HyperlinkButton>());
        }
        finally
        {
            window.Close();
        }
    }

    [AvaloniaFact]
    public void OrderedAndNestedListsRetainTheirStructure()
    {
        var view = new ReleaseNotesMarkdownView
        {
            Markdown = """
                3. Third
                   - Nested
                1. Fourth
                1. Fifth
                """
        };
        var window = new Window
        {
            Content = view
        };

        try
        {
            window.Show();
            window.UpdateLayout();

            var markers = view
                .GetVisualDescendants()
                .OfType<TextBlock>()
                .Where(textBlock => textBlock.Classes.Contains(ReleaseNotesMarkdownView.ListMarkerClass))
                .Select(textBlock => textBlock.Text ?? string.Empty)
                .ToArray();

            Assert.Equal(ExpectedNestedListMarkers, markers);
        }
        finally
        {
            window.Close();
        }
    }

    [AvaloniaFact]
    public void CjkEmphasisAndAutolinksRetainVisibleTextWithoutNavigation()
    {
        var view = new ReleaseNotesMarkdownView
        {
            Markdown = """
                **修复。**这是后续说明

                <https://example.test> <user@example.com>

                **foo*
                """
        };
        var window = new Window
        {
            Content = view
        };

        try
        {
            window.Show();
            window.UpdateLayout();

            var descendants = view.GetVisualDescendants().ToArray();
            var textBlocks = descendants.OfType<TextBlock>().ToArray();
            var visibleText = string.Join('\n', textBlocks.Select(GetText));
            var inlines = GetInlines(textBlocks);

            Assert.Contains("修复。这是后续说明", visibleText, StringComparison.Ordinal);
            Assert.DoesNotContain("**修复。**", visibleText, StringComparison.Ordinal);
            Assert.Contains("https://example.test", visibleText, StringComparison.Ordinal);
            Assert.Contains("user@example.com", visibleText, StringComparison.Ordinal);
            Assert.DoesNotContain("mailto:", visibleText, StringComparison.Ordinal);
            Assert.Contains("*foo", visibleText, StringComparison.Ordinal);
            Assert.Contains(
                inlines,
                inline => inline.Classes.Contains(ReleaseNotesMarkdownView.StrongClass));
            Assert.Equal(
                2,
                inlines.Count(inline => inline.Classes.Contains(ReleaseNotesMarkdownView.LinkClass)));
            Assert.Empty(descendants.OfType<HyperlinkButton>());
        }
        finally
        {
            window.Close();
        }
    }

    [AvaloniaFact]
    public void UpdateDialogAppliesReleaseNoteHierarchyAndSurfaceStyles()
    {
        DesktopTestResources.EnsureProductThemeResources();
        var dialog = new NewVersionAvailableDialog();
        var window = new Window
        {
            Content = dialog
        };

        try
        {
            window.Show();
            var releaseNotes = Assert.IsType<ReleaseNotesMarkdownView>(
                dialog.FindControl<ReleaseNotesMarkdownView>("ReleaseNotesMarkdown"));
            releaseNotes.Markdown = """
                # Release heading

                > Important note

                ```text
                command
                ```
                """;
            window.UpdateLayout();

            var descendants = releaseNotes.GetVisualDescendants().ToArray();
            var heading = Assert.Single(
                descendants.OfType<TextBlock>(),
                textBlock => textBlock.Classes.Contains(ReleaseNotesMarkdownView.HeadingClass));
            var quote = Assert.Single(
                descendants.OfType<Border>(),
                border => border.Classes.Contains(ReleaseNotesMarkdownView.QuoteClass));
            var code = Assert.Single(
                descendants.OfType<Border>(),
                border => border.Classes.Contains(ReleaseNotesMarkdownView.CodeBlockClass));

            Assert.Equal(24, heading.FontSize);
            Assert.Equal(FontWeight.Bold, heading.FontWeight);
            Assert.NotNull(quote.Background);
            Assert.NotNull(code.Background);
        }
        finally
        {
            window.Close();
        }
    }

    private static Inline[] GetInlines(IEnumerable<TextBlock> textBlocks)
    {
        return textBlocks
            .SelectMany(textBlock => textBlock.Inlines ?? [])
            .SelectMany(Flatten)
            .ToArray();
    }

    private static IEnumerable<Inline> Flatten(Inline inline)
    {
        yield return inline;
        if (inline is not Span span)
        {
            yield break;
        }

        foreach (var child in (span.Inlines ?? []).SelectMany(Flatten))
        {
            yield return child;
        }
    }

    private static string GetText(TextBlock textBlock)
    {
        if (!string.IsNullOrEmpty(textBlock.Text))
        {
            return textBlock.Text;
        }

        var builder = new StringBuilder();
        foreach (var inline in textBlock.Inlines ?? [])
        {
            AppendText(builder, inline);
        }

        return builder.ToString();
    }

    private static void AppendText(StringBuilder builder, Inline inline)
    {
        switch (inline)
        {
            case Run run:
                builder.Append(run.Text);
                break;
            case LineBreak:
                builder.AppendLine();
                break;
            case Span span:
                foreach (var child in span.Inlines ?? [])
                {
                    AppendText(builder, child);
                }

                break;
        }
    }
}
