<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DownKyi.Desktop\DownKyi.Desktop.csproj" />
  </ItemGroup>

</Project>
