<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
    <TrimmerRootDescriptor Include="Linker.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Downloader" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="System.Formats.Nrbf" />
    <PackageReference Include="Xaml.Behaviors" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DownKyi.Core\DownKyi.Core.csproj" />
    <ProjectReference Include="..\DownKyi.Application\DownKyi.Application.csproj" />
    <ProjectReference Include="..\DownKyi.Domain\DownKyi.Domain.csproj" />
    <ProjectReference Include="..\DownKyi.Infrastructure\DownKyi.Infrastructure.csproj" />
  </ItemGroup>
</Project>
