using System.Collections.Immutable;
using DownKyi.ArchitectureAnalyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DownKyi.Architecture.Tests;

public sealed class GlobalSqlitePoolCleanupAnalyzerTests
{
    private static readonly string RepositoryRoot = FindRepositoryRoot();
    private static readonly ImmutableArray<MetadataReference> PlatformReferences =
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
        .Split(Path.PathSeparator)
        .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
        .Append((MetadataReference)MetadataReference.CreateFromFile(
            typeof(Microsoft.Data.Sqlite.SqliteConnection).Assembly.Location))
        .ToImmutableArray();

    [Fact]
    public void AnalyzerIsCentralAndCiCompilesDebugAndReleaseConfigurations()
    {
        var props = File.ReadAllText(Path.Combine(RepositoryRoot, "Directory.Build.props"));
        var workflow = File.ReadAllText(Path.Combine(
            RepositoryRoot,
            ".github",
            "workflows",
            "quality.yml"));

        Assert.Contains(
            "DownKyi.ArchitectureAnalyzers.csproj",
            props,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "'$(MSBuildProjectName)' != 'DownKyi.Architecture.Tests'",
            props,
            StringComparison.Ordinal);
        Assert.Contains("-c Release", workflow, StringComparison.Ordinal);
        Assert.Contains("-c Debug", workflow, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }")]
    [InlineData("using static Microsoft.Data.Sqlite.SqliteConnection; class C { void M() => ClearAllPools(); }")]
    [InlineData("using C = Microsoft.Data.Sqlite.SqliteConnection; class T { void M() => C.ClearAllPools(); }")]
    [InlineData("class C { void M() => Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools(); }")]
    [InlineData("using System; using Microsoft.Data.Sqlite; class C { void M() { Action clear = SqliteConnection.ClearAllPools; clear(); } }")]
    [InlineData("using Microsoft.Data.Sqlite; unsafe class C { void M() { delegate* managed<void> clear = &SqliteConnection.ClearAllPools; clear(); } }")]
    public async Task CompilerResolvedInvocationIsRejectedRegardlessOfSyntax(string source)
    {
        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Theory]
    [InlineData("Debug", "DEBUG")]
    [InlineData("Release", "!DEBUG")]
    public async Task SupportedBuildConfigurationsExecuteTheAnalyzer(
        string configuration,
        string symbol)
    {
        var source = $$"""
            using Microsoft.Data.Sqlite;
            class C
            {
            #if {{symbol}}
                void M() => SqliteConnection.ClearAllPools();
            #endif
            }
            """;

        var diagnostics = await AnalyzeAsync(source, configuration).ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task GeneratedCodeIsAnalyzedAndReported()
    {
        const string source = """
            // <auto-generated/>
            using Microsoft.Data.Sqlite;
            class GeneratedOwner { void M() => SqliteConnection.ClearAllPools(); }
            """;

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                path: "GeneratedOwner.g.cs")
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task OwnershipDiagnosticCannotBeSuppressedByCallerSource()
    {
        const string source = """
            using Microsoft.Data.Sqlite;
            class C
            {
            #pragma warning disable DKYI1001
                void M() => SqliteConnection.ClearAllPools();
            #pragma warning restore DKYI1001
            }
            """;

        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task ExplicitProcessOwnerAssemblyIsAllowed()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerPath)
            .ConfigureAwait(true);

        Assert.DoesNotContain(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Theory]
    [InlineData("DownKyi.SystemBenchmarks", "benchmarks/Other/Program.cs")]
    [InlineData("OtherAssembly", "benchmarks/DownKyi.SystemBenchmarks/Program.cs")]
    public async Task ProcessOwnerAllowlistRequiresAssemblyAndSourceIdentity(
        string assemblyName,
        string path)
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";

        var diagnostics = await AnalyzeAsync(source, "Release", assemblyName, path)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task DifferentSymbolsAndScopedCleanupAreAllowed()
    {
        const string source = """
            using Microsoft.Data.Sqlite;
            class Different { public static void ClearAllPools() { } }
            class C
            {
                void M(SqliteConnection connection)
                {
                    Different.ClearAllPools();
                    SqliteConnection.ClearPool(connection);
                }
            }
            """;

        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.DoesNotContain(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(
        string source,
        string configuration,
        string assemblyName = "AdversarialOwner",
        string path = "Source.cs")
    {
        var symbols = configuration switch
        {
            "Debug" => new[] { "DEBUG", "TRACE", "NET", "NET10_0" },
            "Release" => new[] { "TRACE", "NET", "NET10_0" },
            _ => throw new ArgumentOutOfRangeException(nameof(configuration), configuration, null)
        };
        var syntaxTree = CSharpSyntaxTree.ParseText(
            source,
            new CSharpParseOptions(LanguageVersion.Latest, preprocessorSymbols: symbols),
            path);
        var compilation = CSharpCompilation.Create(
            assemblyName,
            [syntaxTree],
            PlatformReferences,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                allowUnsafe: true));
        var analyzer = new GlobalSqlitePoolCleanupAnalyzer();

        return await compilation
            .WithAnalyzers(ImmutableArray.Create<DiagnosticAnalyzer>(analyzer))
            .GetAnalyzerDiagnosticsAsync(TestContext.Current.CancellationToken)
            .ConfigureAwait(false);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "DownKyi.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName
               ?? throw new DirectoryNotFoundException("Could not locate the DownKyi repository root.");
    }
}
