using System.Collections.Immutable;
using DownKyi.ArchitectureAnalyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace DownKyi.Architecture.Tests;

public sealed class GlobalSqlitePoolCleanupAnalyzerTests
{
    private static readonly string RepositoryRoot = FindRepositoryRoot();
    private static readonly ImmutableArray<MetadataReference> PlatformReferences =
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
        .Split(Path.PathSeparator)
        .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
        .Append((MetadataReference)MetadataReference.CreateFromFile(
            typeof(Microsoft.Data.Sqlite.SqliteConnection).Assembly.Location))
        .ToImmutableArray();

    [Fact]
    public void AnalyzerIsCentralAndCiCompilesDebugAndReleaseConfigurations()
    {
        var props = File.ReadAllText(Path.Combine(RepositoryRoot, "Directory.Build.props"));
        var workflow = File.ReadAllText(Path.Combine(
            RepositoryRoot,
            ".github",
            "workflows",
            "quality.yml"));

        Assert.Contains(
            "DownKyi.ArchitectureAnalyzers.csproj",
            props,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "'$(MSBuildProjectName)' != 'DownKyi.Architecture.Tests'",
            props,
            StringComparison.Ordinal);
        Assert.Contains("-c Release", workflow, StringComparison.Ordinal);
        Assert.Contains("-c Debug", workflow, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }")]
    [InlineData("using static Microsoft.Data.Sqlite.SqliteConnection; class C { void M() => ClearAllPools(); }")]
    [InlineData("using C = Microsoft.Data.Sqlite.SqliteConnection; class T { void M() => C.ClearAllPools(); }")]
    [InlineData("class C { void M() => Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools(); }")]
    [InlineData("using System; using Microsoft.Data.Sqlite; class C { void M() { Action clear = SqliteConnection.ClearAllPools; clear(); } }")]
    [InlineData("using Microsoft.Data.Sqlite; unsafe class C { void M() { delegate* managed<void> clear = &SqliteConnection.ClearAllPools; clear(); } }")]
    public async Task CompilerResolvedInvocationIsRejectedRegardlessOfSyntax(string source)
    {
        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Theory]
    [InlineData("Debug", "DEBUG")]
    [InlineData("Release", "!DEBUG")]
    public async Task SupportedBuildConfigurationsExecuteTheAnalyzer(
        string configuration,
        string symbol)
    {
        var source = $$"""
            using Microsoft.Data.Sqlite;
            class C
            {
            #if {{symbol}}
                void M() => SqliteConnection.ClearAllPools();
            #endif
            }
            """;

        var diagnostics = await AnalyzeAsync(source, configuration).ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task GeneratedCodeIsAnalyzedAndReported()
    {
        const string source = """
            // <auto-generated/>
            using Microsoft.Data.Sqlite;
            class GeneratedOwner { void M() => SqliteConnection.ClearAllPools(); }
            """;

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                path: "GeneratedOwner.g.cs")
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task OwnershipDiagnosticCannotBeSuppressedByCallerSource()
    {
        const string source = """
            using Microsoft.Data.Sqlite;
            class C
            {
            #pragma warning disable DKYI1001
                void M() => SqliteConnection.ClearAllPools();
            #pragma warning restore DKYI1001
            }
            """;

        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task ExplicitProcessOwnerAssemblyIsAllowed()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var ownerPath = Path.Combine(
            RepositoryRoot,
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "Program.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                ownerPath,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.DoesNotContain(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Theory]
    [InlineData("DownKyi.SystemBenchmarks", "benchmarks/Other/Program.cs")]
    [InlineData("OtherAssembly", "benchmarks/DownKyi.SystemBenchmarks/Program.cs")]
    public async Task ProcessOwnerAllowlistRequiresAssemblyAndExactRepositoryPath(
        string assemblyName,
        string repositoryRelativePath)
    {
        ArgumentNullException.ThrowIfNull(repositoryRelativePath);
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var path = Path.Combine(
            RepositoryRoot,
            repositoryRelativePath.Replace('/', Path.DirectorySeparatorChar));

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                assemblyName,
                path,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task NestedSuffixPathCannotAcquireProcessOwnership()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var nestedSuffixPath = Path.Combine(
            RepositoryRoot,
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "nested",
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "Program.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                nestedSuffixPath,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task NormalizedExactOwnerPathRemainsTheSameOwner()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var normalizedOwnerPath = Path.Combine(
            RepositoryRoot,
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "nested",
            "..",
            "Program.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                normalizedOwnerPath,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.DoesNotContain(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task AlternateSeparatorCannotTurnNestedSuffixIntoTheOwner()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var alternateSeparator = Path.DirectorySeparatorChar == '/' ? '\\' : '/';
        var nestedSuffixPath = string.Join(
            alternateSeparator,
            RepositoryRoot.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "nested",
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "Program.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                nestedSuffixPath,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task MissingTrustedRepositoryRootFailsClosed()
    {
        const string source =
            "using Microsoft.Data.Sqlite; class C { void M() => SqliteConnection.ClearAllPools(); }";
        var ownerPath = Path.Combine(
            RepositoryRoot,
            "benchmarks",
            "DownKyi.SystemBenchmarks",
            "Program.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                ownerPath)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task SourceLineDirectiveCannotForgeOwnerPath()
    {
        const string source = """
            #line 1 "benchmarks/DownKyi.SystemBenchmarks/Program.cs"
            using Microsoft.Data.Sqlite;
            class C { void M() => SqliteConnection.ClearAllPools(); }
            """;
        var nonOwnerPath = Path.Combine(RepositoryRoot, "AdversarialOwner.cs");

        var diagnostics = await AnalyzeAsync(
                source,
                "Release",
                GlobalSqlitePoolCleanupAnalyzer.AllowedProcessOwnerAssembly,
                nonOwnerPath,
                RepositoryRoot)
            .ConfigureAwait(true);

        Assert.Contains(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task DifferentSymbolsAndScopedCleanupAreAllowed()
    {
        const string source = """
            using Microsoft.Data.Sqlite;
            class Different { public static void ClearAllPools() { } }
            class C
            {
                void M(SqliteConnection connection)
                {
                    Different.ClearAllPools();
                    SqliteConnection.ClearPool(connection);
                }
            }
            """;

        var diagnostics = await AnalyzeAsync(source, "Release").ConfigureAwait(true);

        Assert.DoesNotContain(diagnostics, diagnostic =>
            diagnostic.Id == GlobalSqlitePoolCleanupAnalyzer.DiagnosticId);
    }

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(
        string source,
        string configuration,
        string assemblyName = "AdversarialOwner",
        string path = "Source.cs",
        string? repositoryRoot = null)
    {
        var symbols = configuration switch
        {
            "Debug" => new[] { "DEBUG", "TRACE", "NET", "NET10_0" },
            "Release" => new[] { "TRACE", "NET", "NET10_0" },
            _ => throw new ArgumentOutOfRangeException(nameof(configuration), configuration, null)
        };
        var syntaxTree = CSharpSyntaxTree.ParseText(
            source,
            new CSharpParseOptions(LanguageVersion.Latest, preprocessorSymbols: symbols),
            path);
        var compilation = CSharpCompilation.Create(
            assemblyName,
            [syntaxTree],
            PlatformReferences,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                allowUnsafe: true));
        var analyzer = new GlobalSqlitePoolCleanupAnalyzer();
        var repositoryRootMarker = repositoryRoot == null
            ? null
            : new TestAdditionalText(Path.Combine(repositoryRoot, "Directory.Build.targets"));
        var additionalFiles = repositoryRootMarker == null
            ? ImmutableArray<AdditionalText>.Empty
            : ImmutableArray.Create<AdditionalText>(repositoryRootMarker);
        var analyzerOptions = new AnalyzerOptions(
            additionalFiles,
            new TestAnalyzerConfigOptionsProvider(repositoryRootMarker));

        return await compilation
            .WithAnalyzers(
                ImmutableArray.Create<DiagnosticAnalyzer>(analyzer),
                analyzerOptions)
            .GetAnalyzerDiagnosticsAsync(TestContext.Current.CancellationToken)
            .ConfigureAwait(false);
    }

    private sealed class TestAnalyzerConfigOptionsProvider(
        AdditionalText? repositoryRootMarker)
        : AnalyzerConfigOptionsProvider
    {
        private static readonly AnalyzerConfigOptions Empty =
            new TestAnalyzerConfigOptions(new Dictionary<string, string>());

        public override AnalyzerConfigOptions GlobalOptions { get; } =
            Empty;

        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => Empty;

        public override AnalyzerConfigOptions GetOptions(AdditionalText textFile) =>
            ReferenceEquals(textFile, repositoryRootMarker)
                ? new TestAnalyzerConfigOptions(
                    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                    {
                        [GlobalSqlitePoolCleanupAnalyzer.RepositoryRootMarkerMetadata] = "true"
                    })
                : Empty;
    }

    private sealed class TestAnalyzerConfigOptions(
        IReadOnlyDictionary<string, string> values) : AnalyzerConfigOptions
    {
        public override bool TryGetValue(string key, out string value) =>
            values.TryGetValue(key, out value!);
    }

    private sealed class TestAdditionalText(string path) : AdditionalText
    {
        public override string Path { get; } = path;

        public override SourceText GetText(CancellationToken cancellationToken = default) =>
            SourceText.From(string.Empty);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "DownKyi.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName
               ?? throw new DirectoryNotFoundException("Could not locate the DownKyi repository root.");
    }
}
