<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DownKyi.Architecture.Tests" />
    <InternalsVisibleTo Include="DownKyi.Windows.Tests" />
    <InternalsVisibleTo Include="DownKyi.MacOS.Tests" />
    <InternalsVisibleTo Include="DownKyi.Linux.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DownKyi.ProcessSupervision\DownKyi.ProcessSupervision.csproj" />
  </ItemGroup>

</Project>
